version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lumen_app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    networks:
      - app_network
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=productapp
      - DB_USERNAME=productapp
      - DB_PASSWORD=Doc7Yeg4H3
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: lumen_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: productapp
      MYSQL_USER: productapp
      MYSQL_PASSWORD: Doc7Yeg4H3
    ports:
      - "3307:3306"
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/mysql

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
